### PR TITLE
Disable sticky

### PR DESCRIPTION
**Pull request by highergroundstudio**
I needed to add this functionality to my website so I thought that it would make StickyScroll better.

### CODE REVIEW

**Comment by rickharris** [comment]
I actually needed to be able to disable it recently as well, and now basic implementation of disabling already in StickyScroll; you can call it with `.stickyScroll('reset')`

I'm not 100% satisfied with that approach... I don't like how it introduces new, pseudo-private jQuery functions and I don't know how it would behave with multiple "sticky" elements on a page. But I do intend to keep the features associated with disabling StickyScroll minimalistic, and this commit is a little bit more than I think belongs in the main branch.

I have two notes for you on your code:
1. I use an anonymous function to protect the `$` function name, so you can use it without fear instead of the full `jQuery` function.
2. All of StickyScroll's events are namespaced as such, so when you unbind events you can use `$(window).unbind('.stickyscroll')` to unbind only those events associated with this plugin, without stepping on the toes of any other script that may have bound events to the window.

Thanks so much for contributing to StickyScroll. You're actually my first pull request.

-Rick

**Comment by highergroundstudio** [comment]
I tried your reset but it just makes the sticky container git stuck where you push the button rather than send it back to its original position before being pulled down by sticky. I would rather have a little more code and more control. That is more of my approach. Glad to be the first pull request. When I get my site up i'll give you the url so you can have it as a website that uses stickyscroll. Thanks for the plugin by the way.

**Comment by rickharris** [comment]
That's interesting. The reset should've unset any positioning. I pushed some pretty major changes last night, including an updated reset method, but I don't think functionally it's any different than before. I'll have to do some more testing.

**Comment by highergroundstudio** [comment]
I'll try the new changes later.

**Pull request closed without merging**
